name: AWS Project 4
on: [push]

jobs:

  create_infra:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::775698064297:role/project4-role
        aws-region: eu-west-3

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.15.0"
        terraform_wrapper: false

    - name: 'apply terraform'
      run: |
        cd aws && terraform init
        terraform apply -auto-approve
    
  build_and_push:
    needs: create_infra
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    
    - uses: 'actions/checkout@v4'
    
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::775698064297:role/project4-role
        aws-region: eu-west-3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: 'Build images'
      run: |-
        docker build -t ${{ steps.login-ecr.outputs.registry }}/my-repository/frontend:${{ github.sha }} frontend/
        docker build -t ${{ steps.login-ecr.outputs.registry }}/my-repository/backend:${{ github.sha }} api/

    
    - name: 'Push images'
      run: |-
        docker push us-central1-docker.pkg.dev/project-55dcf55b-027c-4122-a45/my-repository/frontend:${{ github.sha }}

        docker push us-central1-docker.pkg.dev/project-55dcf55b-027c-4122-a45/my-repository/backend:${{ github.sha }}
