name: Project 4
on: [push]

jobs:

  create_infra:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v3'
      with:
        service_account: 'project4-sa@project-55dcf55b-027c-4122-a45.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/1073687322815/locations/global/workloadIdentityPools/github-project4/providers/github'
        token_format: 'access_token'

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.15.0"
        terraform_wrapper: false

    - name: 'apply terraform'
      run: |
        cd gcp && terraform init
        terraform apply -auto-approve
  
  build_and_push:
    needs: create_infra
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v3'
      with:
        service_account: 'project4-sa@project-55dcf55b-027c-4122-a45.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/1073687322815/locations/global/workloadIdentityPools/github-project4/providers/github'
        token_format: 'access_token'

    - name: 'Docker Auth'
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: 'Build and Push'
      run: |-
        docker build -t us-central1-docker.pkg.dev/project-55dcf55b-027c-4122-a45/my-repository/frontend:${{ github.sha }} frontend/
        docker push us-central1-docker.pkg.dev/project-55dcf55b-027c-4122-a45/my-repository/frontend:${{ github.sha }}

        docker build -t us-central1-docker.pkg.dev/project-55dcf55b-027c-4122-a45/my-repository/backend:${{ github.sha }} api/
        docker push us-central1-docker.pkg.dev/project-55dcf55b-027c-4122-a45/my-repository/backend:${{ github.sha }}